name: publish

on:
  pull_request:
    types: [closed]
    branches:
      - release

jobs:
  publish: 
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        run: |
          git config user.name milo
          git config user.email mazihang@codemao.cn

      - name: setup zh-cn timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
          
      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm install

      - name: execute code lint
        run: npm run lint

      - name: execute unit test
      
        run: npm run test

      - name: build dist
        run: npm run dist
      
      - name: publish
        run: npm run publish
      
      - name: Get the published version
        id: vars
        run: echo ::set-output name=ref::${GITHUB_REF#refs/*/}

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.ref }}
          release_name: ${{ steps.vars.outputs.ref }}
          body_path: "${{ github.workspace }}/CHANGELOG.md"
          draft: true
          prerelease: false
        
      # - name: npm publish
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
